apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helmet-duckdns
spec:
  secretName: helmet-duckdns-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
    - yourname.duckdns.org
