apiVersion: v1
kind: Namespace
metadata:
  name: helmet-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: helmet-production
  labels:
    environment: production
