apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helmet-production

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/public-endpoint.yaml
  - path: patches/replicas.yaml
  - target:
      kind: ClusterRoleBinding
      name: traefik
    path: patches/traefik-rbac-subject.yaml

labels:
  - pairs:
      environment: production
