apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helmet-violation
resources:
  - namespace.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - secrets.example.yaml
