apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: auth
  ports:
    - name: http
      port: 8001
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
