apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app.kubernetes.io/component: ingestion
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: ingestion
  ports:
    - name: http
      port: 8002
      targetPort: http
