apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/component: notification
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: notification
  ports:
    - name: http
      port: 8003
      targetPort: http
