apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helmet-staging

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/public-endpoint.yaml
  - path: patches/secrets.yaml
  - path: patches/replicas.yaml

labels:
  - pairs:
      environment: staging
