# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"F\n\x13VerifyTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"(\n\x15GetUserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"^\n\x16GetUserProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t2\x9e\x01\n\x0b\x41uthService\x12\x42\n\x0bVerifyToken\x12\x18.auth.VerifyTokenRequest\x1a\x19.auth.VerifyTokenResponse\x12K\n\x0eGetUserProfile\x12\x1b.auth.GetUserProfileRequest\x1a\x1c.auth.GetUserProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYTOKENREQUEST']._serialized_start=20
  _globals['_VERIFYTOKENREQUEST']._serialized_end=55
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=57
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=127
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=129
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=169
  _globals['_GETUSERPROFILERESPONSE']._serialized_start=171
  _globals['_GETUSERPROFILERESPONSE']._serialized_end=265
  _globals['_AUTHSERVICE']._serialized_start=268
  _globals['_AUTHSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
