apiVersion: v1
kind: ConfigMap
metadata:
  name: helmet-runtime-config
data:
  ENVIRONMENT: staging
  NEXT_PUBLIC_API_URL: https://dtdat-nthv.duckdns.org
  NEXT_PUBLIC_WS_URL: wss://dtdat-nthv.duckdns.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: helmet-public-routes
spec:
  routes:
    - match: Host(`dtdat-nthv.duckdns.org`) && PathPrefix(`/api/v1/videos`)
      kind: Rule
      services:
        - name: ingestion
          port: 8002
    - match: Host(`dtdat-nthv.duckdns.org`) && PathPrefix(`/api/v1/violations`)
      kind: Rule
      services:
        - name: dashboard
          port: 8004
    - match: Host(`dtdat-nthv.duckdns.org`) && PathPrefix(`/ws/status`)
      kind: Rule
      services:
        - name: notification
          port: 8003
    - match: Host(`dtdat-nthv.duckdns.org`) && PathPrefix(`/ws/camera`)
      kind: Rule
      services:
        - name: realtime-stream
          port: 8005
    - match: Host(`dtdat-nthv.duckdns.org`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helmet-duckdns
spec:
  dnsNames:
    - dtdat-nthv.duckdns.org
