apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-worker
spec:
  replicas: 1
