apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-reference
  labels:
    app.kubernetes.io/component: redis
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
