apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestion
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestration
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-worker
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-stream
  annotations:
    iam.gke.io/gcp-service-account: helmet-runtime@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
